@v1=http://127.0.0.1:3000/v1

### Health
GET {{v1}}/health HTTP/1.1

### Account create
POST {{v1}}/account HTTP/1.1
Content-Type: application/json

{
  "name": "Tester",
  "email": "test@test.comd",
  "password": "123aA123",
  "username": "abbs"
}

### Account sign in
POST {{v1}}/account/session HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.comd",
  "password": "123aA123"
}
